const LONG_WORD_THRESHOLD = 5;

const syllableOverrides: Record<string, string[]> = {
  Affe: ['Af', 'fe'],
  Ameise: ['A', 'mei', 'se'],
  Ampel: ['Am', 'pel'],
  Ananas: ['A', 'na', 'nas'],
  Angel: ['An', 'gel'],
  Apfel: ['Ap', 'fel'],
  Banane: ['Ba', 'na', 'ne'],
  Batterie: ['Bat', 'te', 'rie'],
  Brille: ['Bril', 'le'],
  Bruecke: ['Brü', 'cke'],
  Brücke: ['Brü', 'cke'],
  Cafe: ['Ca', 'fe'],
  Café: ['Ca', 'fé'],
  Chamaeleon: ['Cha', 'mä', 'le', 'on'],
  Chamäleon: ['Cha', 'mä', 'le', 'on'],
  Computer: ['Com', 'pu', 'ter'],
  Delfin: ['Del', 'fin'],
  Dino: ['Di', 'no'],
  Dose: ['Do', 'se'],
  Drache: ['Dra', 'che'],
  Dusche: ['Du', 'sche'],
  Eimer: ['Ei', 'mer'],
  Elefant: ['E', 'le', 'fant'],
  Ente: ['En', 'te'],
  Erdbeere: ['Erd', 'bee', 're'],
  Esel: ['E', 'sel'],
  Fahrrad: ['Fahr', 'rad'],
  Feder: ['Fe', 'der'],
  Fernseher: ['Fern', 'se', 'her'],
  Flasche: ['Fla', 'sche'],
  Fliege: ['Flie', 'ge'],
  Gabel: ['Ga', 'bel'],
  Geschenk: ['Ge', 'schenk'],
  Giraffe: ['Gi', 'raf', 'fe'],
  Gitarre: ['Gi', 'tar', 're'],
  Gurke: ['Gur', 'ke'],
  Hammer: ['Ham', 'mer'],
  Hase: ['Ha', 'se'],
  Hexe: ['He', 'xe'],
  Hose: ['Ho', 'se'],
  Igel: ['I', 'gel'],
  Iglu: ['I', 'glu'],
  Insel: ['In', 'sel'],
  Israel: ['Is', 'ra', 'el'],
  Jacke: ['Ja', 'cke'],
  Joghurt: ['Jo', 'ghurt'],
  Jupiter: ['Ju', 'pi', 'ter'],
  Kamel: ['Ka', 'mel'],
  Katze: ['Kat', 'ze'],
  Kerze: ['Ker', 'ze'],
  Kuchen: ['Ku', 'chen'],
  Laterne: ['La', 'ter', 'ne'],
  Loeffel: ['Löf', 'fel'],
  Löffel: ['Löf', 'fel'],
  Loewe: ['Lö', 'we'],
  Löwe: ['Lö', 'we'],
  Mango: ['Man', 'go'],
  Messer: ['Mes', 'ser'],
  Moehre: ['Möh', 're'],
  Möhre: ['Möh', 're'],
  Nase: ['Na', 'se'],
  Nashorn: ['Nas', 'horn'],
  Nilpferd: ['Nil', 'pferd'],
  Nudeln: ['Nu', 'deln'],
  Oktopus: ['Ok', 'to', 'pus'],
  Olive: ['O', 'li', 've'],
  Omelett: ['O', 'me', 'lett'],
  Orange: ['O', 'ran', 'ge'],
  Panda: ['Pan', 'da'],
  Papagei: ['Pa', 'pa', 'gei'],
  Pinguin: ['Pin', 'gu', 'in'],
  Pizza: ['Piz', 'za'],
  Pommes: ['Pom', 'mes'],
  Quadrat: ['Qua', 'drat'],
  Qualle: ['Qual', 'le'],
  Regenbogen: ['Re', 'gen', 'bo', 'gen'],
  Regenschirm: ['Re', 'gen', 'schirm'],
  Roboter: ['Ro', 'bo', 'ter'],
  Rose: ['Ro', 'se'],
  Rucksack: ['Ruck', 'sack'],
  Schere: ['Sche', 're'],
  Schildkroete: ['Schild', 'krö', 'te'],
  Schildkröte: ['Schild', 'krö', 'te'],
  Schlange: ['Schlan', 'ge'],
  Schmetterling: ['Schmet', 'ter', 'ling'],
  Schnecke: ['Schne', 'cke'],
  Schneemann: ['Schnee', 'mann'],
  Sofa: ['So', 'fa'],
  Sonne: ['Son', 'ne'],
  Taube: ['Tau', 'be'],
  Telefon: ['Te', 'le', 'fon'],
  Teller: ['Tel', 'ler'],
  Tiger: ['Ti', 'ger'],
  Tomate: ['To', 'ma', 'te'],
  Traktor: ['Trak', 'tor'],
  Traube: ['Trau', 'be'],
  'U-Boot': ['U', 'Boot'],
  Umarmung: ['Um', 'ar', 'mung'],
  Unterhose: ['Un', 'ter', 'ho', 'se'],
  Vase: ['Va', 'se'],
  Ventilator: ['Ven', 'ti', 'la', 'tor'],
  Vogel: ['Vo', 'gel'],
  Waffel: ['Waf', 'fel'],
  Wagen: ['Wa', 'gen'],
  Wassermelone: ['Was', 'ser', 'me', 'lo', 'ne'],
  Wespe: ['Wes', 'pe'],
  Xylophon: ['Xy', 'lo', 'phon'],
  'Yo-Yo': ['Yo', 'Yo'],
  Zebra: ['Ze', 'bra'],
  Ziege: ['Zie', 'ge'],
  Zitrone: ['Zi', 'tro', 'ne'],
  Zwiebel: ['Zwie', 'bel'],
};

export const getWordSyllables = (word: string): string[] => (
  syllableOverrides[word] ?? word.split('')
);

export const getWordScrambleUnits = (word: string): string[] => {
  if (word.length <= LONG_WORD_THRESHOLD) {
    return word.split('');
  }

  return getWordSyllables(word);
};

export const canScrambleWord = (word: string | null | undefined): word is string => (
  Boolean(word && getWordScrambleUnits(word).length > 1)
);
